   {
     * "id": 40,
     * "sku": "Cup-2",
      *"ebay_account_id": 1,
     * "title": "Copeland Spode Queen Elizabeth II 1953 Coronation Mug Tankard",
     * "description": "This is a Copeland Spode mug commemorating the coronation of Queen Elizabeth II on June 2nd, 1953. The mug has a creamy white glaze with brown transfer printing and coloured crests. It features a portrait of Queen Elizabeth II, the royal crest, and text marking the occasion.",
     * "condition_description": "Used condition with staining and minor chips around the rims. The glaze is crazed and discolored. There are marks and scuffs on the exterior surface.",
     * "suggested_price": 12,
      "processing_status": "processed",
      "published_to_ebay": 0,
      "ebay_item_id": null,
      "created_at": "2025-06-04 06:25:54",
      "updated_at": "2025-06-04 06:31:05",
      "processing_status_updated_at": "2025-06-04 06:31:04",
      "ai_processed": 1,
      "category_suggestion_id": 1676,
     * "selected_category_path": "Historical Memorabilia >> Collectables >> Royalty Collectables",
     * "selected_ebay_category_id": "39630",
      "images": [
        {
          "id": 139,
          "sku": "Cup-2",
          "ebay_account_id": 1,
          "session_id": 81,
     *     "b2_url": "https://eBayImages.s3.us-east-005.backblazeb2.com/ebay_images/Cup-2/Cup-2-1_81.jpg",
          "original_filename": "image_4.jpg",
          "image_index": 1,
          "display_order": 1,
          "is_deleted": 0,
          "zoom_level": 1,
          "upload_date": "2025-06-04 06:25:58",
          "content_type": "image/jpeg"
        },
        {
          "id": 136,
          "sku": "Cup-2",
          "ebay_account_id": 1,
          "session_id": 78,
     *     "b2_url": "https://eBayImages.s3.us-east-005.backblazeb2.com/ebay_images/Cup-2/Cup-2-1_78.jpg",
          "original_filename": "image_1.jpg",
          "image_index": 1,
          "display_order": 2,
          "is_deleted": 0,
          "zoom_level": 1,
          "upload_date": "2025-06-04 06:25:56",
          "content_type": "image/jpeg"
        },
        {
          "id": 138,
          "sku": "Cup-2",
          "ebay_account_id": 1,
          "session_id": 80,
      *    "b2_url": "https://eBayImages.s3.us-east-005.backblazeb2.com/ebay_images/Cup-2/Cup-2-1_80.jpg",
          "original_filename": "image_2.jpg",
          "image_index": 1,
          "display_order": 3,
          "is_deleted": 0,
          "zoom_level": 1,
          "upload_date": "2025-06-04 06:25:57",
          "content_type": "image/jpeg"
        },
        {
          "id": 140,
          "sku": "Cup-2",
          "ebay_account_id": 1,
          "session_id": 82,
     *     "b2_url": "https://eBayImages.s3.us-east-005.backblazeb2.com/ebay_images/Cup-2/Cup-2-1_82.jpg",
          "original_filename": "image_3.jpg",
          "image_index": 1,
          "display_order": 4,
          "is_deleted": 0,
          "zoom_level": 1,
          "upload_date": "2025-06-04 06:25:59",
          "content_type": "image/jpeg"
        },
        {
          "id": 137,
          "sku": "Cup-2",
          "ebay_account_id": 1,
          "session_id": 79,
     *     "b2_url": "https://eBayImages.s3.us-east-005.backblazeb2.com/ebay_images/Cup-2/Cup-2-1_79.jpg",
          "original_filename": "image_5.jpg",
          "image_index": 1,
          "display_order": 5,
          "is_deleted": 0,
          "zoom_level": 1,
          "upload_date": "2025-06-04 06:25:56",
          "content_type": "image/jpeg"
        },
        {
          "id": 135,
          "sku": "Cup-2",
          "ebay_account_id": 1,
          "session_id": 77,
     *     "b2_url": "https://eBayImages.s3.us-east-005.backblazeb2.com/ebay_images/Cup-2/Cup-2-1_77.jpg",
          "original_filename": "image_0.jpg",
          "image_index": 1,
          "display_order": 6,
          "is_deleted": 0,
          "zoom_level": 1,
          "upload_date": "2025-06-04 06:25:55",
          "content_type": "image/jpeg"
        }
      ],
      "image_count": 6,
      "first_image_url": "https://eBayImages.s3.us-east-005.backblazeb2.com/ebay_images/Cup-2/Cup-2-1_81.jpg"
    }